# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('person_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 8, 13, 13, 37, 425021, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='date_of_processing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20),
        ),
    ]
