# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_auth', '0002_auto_20160708_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
