# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person_auth', '0003_number_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='date_of_processing',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 8, 13, 17, 59, 558647, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
